# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('sexo', models.BooleanField()),
                ('telefono_casa', models.IntegerField()),
                ('telefono_padre', models.IntegerField()),
                ('telefono_madre', models.IntegerField()),
                ('telefono_familiar', models.IntegerField()),
                ('telefono_vecino', models.IntegerField()),
                ('enfermedad_relevante', models.CharField(max_length=40)),
                ('con_quien_vive', models.CharField(max_length=40)),
                ('quien_lo_trae', models.CharField(max_length=40)),
                ('telefono_que_lo_trae', models.IntegerField()),
                ('utiliza_transporte', models.BooleanField()),
                ('tiene_obra_social', models.BooleanField()),
                ('obra_social_nombre', models.CharField(max_length=40, null=True)),
                ('obra_social_numero', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autorizado',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('sexo', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Padre_madre',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('sexo', models.BooleanField()),
                ('cant_hijos_en_colegio', models.IntegerField()),
                ('profesion', models.CharField(max_length=40)),
                ('telefono_trabajo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('sexo', models.BooleanField()),
                ('telefono_particular_p', models.IntegerField()),
                ('telefono_laboral_p', models.IntegerField()),
                ('telefono_familiar_p', models.IntegerField()),
                ('datos_familiares_cargo', models.TextField(max_length=300)),
                ('fecha_inicio_actividad', models.DateTimeField()),
                ('antecedentes_laborales', models.TextField(max_length=300)),
                ('antiguedad_en_empresa', models.DateTimeField()),
                ('estudios_cursados', models.TextField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('domicilio', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('sexo', models.BooleanField()),
                ('nombre_transporte', models.CharField(max_length=40)),
                ('telefono_transportista', models.IntegerField()),
                ('detalles_transportista', models.TextField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='autorizados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Autorizado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='padres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Padre_madre'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Transportista'),
        ),
    ]
