# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorizado',
            name='autorizacion',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
