# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculacion',
            name='matriculado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('Re', 'Re')], max_length=2, verbose_name='Estado'),
        ),
    ]
