# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='seccion_asignada',
            field=models.ForeignKey(blank=True, default=32, on_delete=django.db.models.deletion.CASCADE, to='institucion.Seccion'),
            preserve_default=False,
        ),
    ]
