# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20181026_1833'),
        ('matriculacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno_curso',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='alumno_curso',
            name='curso',
        ),
        migrations.AddField(
            model_name='matriculacion',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matriculacion',
            name='matriculado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('Re', 'Re'), ('Eg', 'Eg'), ('Pe', 'Pe')], max_length=2, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='alumno_Curso',
        ),
    ]
