# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='seccion_asignada',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Seccion'),
        ),
    ]
