# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-02 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='numero_afiliado_obra_social',
        ),
    ]
