# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-09 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20180725_0239'),
        ('matriculacion', '0002_auto_20180807_1200'),
        ('matriculacion', '0002_auto_20180802_1746'),
    ]

    operations = [
    ]
