# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20181105_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculacion',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso'),
        ),
    ]
