# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20180828_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='autorizados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Autorizado'),
        ),
    ]
