# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_autorizado_autorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padre_madre',
            name='cant_hijos_en_colegio',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido de la Persona'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='con_quien_vive',
            field=models.CharField(max_length=40, verbose_name='Con quien vive'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio de la Persona'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email de la Persona'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='enfermedad_relevante',
            field=models.CharField(max_length=40, null=True, verbose_name='Enfermedad relevante'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Persona'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='obra_social_nombre',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre Obra Social'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='obra_social_numero',
            field=models.IntegerField(verbose_name='Num Obra Social'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='quien_lo_trae',
            field=models.CharField(max_length=40, verbose_name='Quien lo trae'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo de la Persona(True = Hombre)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_casa',
            field=models.IntegerField(verbose_name='Telefono de la Casa'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_familiar',
            field=models.IntegerField(null=True, verbose_name='Telefono de algun Familiar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_madre',
            field=models.IntegerField(null=True, verbose_name='Telefono de la Madre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_padre',
            field=models.IntegerField(null=True, verbose_name='Telefono del Padre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_que_lo_trae',
            field=models.IntegerField(verbose_name='Telefono de quien lo trae'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_vecino',
            field=models.IntegerField(null=True, verbose_name='Telefono de algun Vecino'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tiene_obra_social',
            field=models.BooleanField(verbose_name='Tiene obra o no'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='utiliza_transporte',
            field=models.BooleanField(verbose_name='Viene o no en transporte'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido de la Persona'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='autorizacion',
            field=models.BooleanField(verbose_name='Esta autorizado o no'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio de la Persona'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email de la Persona'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Persona'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo de la Persona(True = Hombre)'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido de la Persona'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio de la Persona'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email de la Persona'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Persona'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='profesion',
            field=models.CharField(max_length=40, verbose_name='Profesion del Padre/Madre'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo de la Persona(True = Hombre)'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='telefono_trabajo',
            field=models.IntegerField(verbose_name='Telefono del Trabajo del Padre/Madre'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='antecedentes_laborales',
            field=models.TextField(max_length=300, verbose_name='Datos de Trabajos Previos'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='antiguedad_en_empresa',
            field=models.DateTimeField(verbose_name='Antiguedad en la Empresa'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido de la Persona'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='datos_familiares_cargo',
            field=models.TextField(max_length=300, verbose_name='Nombre y Apellido de familiar del docente'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio de la Persona'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email de la Persona'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estudios_cursados',
            field=models.TextField(max_length=300, verbose_name='Estudios del Profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_inicio_actividad',
            field=models.DateTimeField(verbose_name='Fecha de Inicio de Clases en el Colegio'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Persona'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo de la Persona(True = Hombre)'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono_familiar_p',
            field=models.IntegerField(verbose_name='Telefono de algun Familiar del Profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono_laboral_p',
            field=models.IntegerField(verbose_name='Telefono Laboral del Profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono_particular_p',
            field=models.IntegerField(verbose_name='Telefono Personal del Profesor'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido de la Persona'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='detalles_transportista',
            field=models.TextField(max_length=300, verbose_name='Detalles del Transportista'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio de la Persona'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email de la Persona'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de la Persona'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='nombre_transporte',
            field=models.CharField(max_length=40, verbose_name='Nombre del Transporte'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo de la Persona(True = Hombre)'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='telefono_transportista',
            field=models.IntegerField(verbose_name='Telefono del Transportista'),
        ),
    ]
