# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20180920_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='matriculado',
        ),
    ]
