# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20181007_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='lugar_nacimiento',
            field=models.CharField(max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='domicilio',
            field=models.CharField(max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='lugar_nacimiento',
            field=models.CharField(max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='domicilio',
            field=models.CharField(max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='lugar_nacimiento',
            field=models.CharField(max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='domicilio',
            field=models.CharField(max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='lugar_nacimiento',
            field=models.CharField(max_length=150, verbose_name='Lugar de Nacimiento'),
        ),
    ]
