# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20181017_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='user',
            new_name='secretaria',
        ),
    ]
