# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0003_auto_20181017_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_social',
            name='nombre',
            field=models.CharField(default='asdf', max_length=40, unique=True, verbose_name='Nombre Obra Social'),
            preserve_default=False,
        ),
    ]
