# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0003_auto_20180515_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni de la persona'),
        ),
    ]
