# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0003_remove_alumno_matriculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='padres',
        ),
        migrations.AddField(
            model_name='familia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Alumno'),
        ),
        migrations.AddField(
            model_name='familia',
            name='padre_madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Padre_madre'),
        ),
    ]
