# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20180923_1731'),
        ('matriculacion', '0004_auto_20180923_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion_alumno',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='asignacion_alumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Asignacion_Alumno',
        ),
    ]
