# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0004_auto_20181019_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno_Autorizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion_con_alumno', models.TextField(max_length=50, verbose_name='Que relacion tiene con el alumno')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Alumno')),
            ],
        ),
        migrations.RemoveField(
            model_name='autorizado',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='autorizado',
            name='relacion_con_alumno',
        ),
        migrations.AddField(
            model_name='alumno_autorizado',
            name='autorizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Autorizado'),
        ),
    ]
