# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0005_auto_20181008_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usa_obra_social',
            old_name='obra_social_numero',
            new_name='numero_afiliado',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='numero_afiliado_obra_social',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
    ]
