# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0006_auto_20180923_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='con_quien_vive',
            field=models.CharField(default=23, max_length=40, verbose_name='Con quien vive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='quien_lo_trae',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='Quien lo trae'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono_que_lo_trae',
            field=models.IntegerField(default=523452, verbose_name='Telefono de quien lo trae'),
            preserve_default=False,
        ),
    ]
