# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0006_auto_20181009_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra_social',
            old_name='obra_social_nombre',
            new_name='nombre',
        ),
    ]
