# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0007_auto_20180628_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
