# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0007_auto_20180923_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
    ]
