# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0009_auto_20180626_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='antiguedad_en_empresa',
            field=models.DateField(verbose_name='Antiguedad en la Empresa'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_inicio_actividad',
            field=models.DateField(verbose_name='Fecha de Inicio de Clases en el Colegio'),
        ),
    ]
