# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0009_auto_20180701_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='autorizado',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='padre_madre',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='transportista',
            name='fecha_nacimiento',
        ),
    ]
