# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0010_remove_alumno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculacion',
            name='fecha_matriculacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Matriculacion'),
        ),
    ]
