# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0012_merge_20180628_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-10-10', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-10-10', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='autorizado',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-10-10', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='padre_madre',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-10-10', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='apellido',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Dni'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='domicilio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-10-10', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transportista',
            name='sexo',
            field=models.BooleanField(verbose_name='Sexo'),
        ),
    ]
