# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20180923_1731'),
        ('matriculacion', '0012_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='alumno_curso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='matriculacion.Alumno'),
        ),
        migrations.AddField(
            model_name='alumno_curso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso'),
        ),
    ]
