# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0014_auto_20181001_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='numero_afiliado_obra_social',
            field=models.IntegerField(null=True, verbose_name='Numero de Afiliado'),
        ),
        migrations.AddField(
            model_name='obra_social',
            name='numero',
            field=models.IntegerField(default=45, verbose_name='Numero de Contacto'),
            preserve_default=False,
        ),
    ]
