# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-02 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_remove_alumno_numero_afiliado_obra_social'),
        ('matriculacion', '0015_auto_20181001_2250'),
    ]

    operations = [
    ]
