# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0016_merge_20181002_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='numero_afiliado_obra_social',
            field=models.IntegerField(null=True, verbose_name='Numero de Afiliado'),
        ),
    ]
