# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='titulo',
        ),
    ]
