# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificacion', models.CharField(choices=[('Habilitar', 'Habilitar'), ('Deshabilitar', 'Deshabilitar'), ('Eliminar', 'Eliminar'), ('Crear', 'Crear'), ('Editar', 'Editar')], max_length=2, verbose_name='Modificacion')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='autor',
            field=models.CharField(default=3, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='cantidad_paginas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='editorial',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fecha_lanzamiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='genero',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tipo',
            field=models.CharField(default=4, max_length=50, verbose_name='Libro, Texto, Ejercicios, etc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AddField(
            model_name='estado',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Document'),
        ),
        migrations.AddField(
            model_name='estado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
