# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documento',
        ),
    ]
