# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_estado_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Accion', 'Accion'), ('Ciencia Ficcion', 'Ciencia Ficcion'), ('Terror', 'Terror'), ('Aventura', 'Aventura'), ('Policial', 'Policial'), ('Politica', 'Politica'), ('Fantasia', 'Fantasia'), ('Otros', 'Otros')], max_length=15, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='document',
            name='habilitado',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', max_length=13, verbose_name='Habilitado'),
        ),
    ]
