# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20180611_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='modificacion',
            field=models.CharField(choices=[('Habilitar', 'Habilitar'), ('Deshabilitar', 'Deshabilitar'), ('Eliminar', 'Eliminar'), ('Crear', 'Crear'), ('Editar', 'Editar')], max_length=12, verbose_name='Modificacion'),
        ),
    ]
