# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20180921_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
