# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20180622_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cantidad_paginas',
        ),
        migrations.RemoveField(
            model_name='document',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='document',
            name='fecha_lanzamiento',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='genero',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Accion', 'Accion'), ('Ciencia Ficcion', 'Ciencia Ficcion'), ('Terror', 'Terror'), ('Aventura', 'Aventura'), ('Policial', 'Policial'), ('Politica', 'Politica'), ('Fantacia', 'Fantacia'), ('Otros', 'Otros')], default=34, max_length=15, verbose_name='Modificacion'),
            preserve_default=False,
        ),
    ]
