# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_auto_20180627_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='autor',
        ),
    ]
