# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculacion', '0006_matriculacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('profesor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculacion.Profesor')),
            ],
            options={
                'abstract': False,
            },
            bases=('matriculacion.profesor',),
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNo', models.CharField(max_length=5, verbose_name='1ero, 2do, etc...')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=1, verbose_name='A-B-C-D')),
                ('grado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('profesor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='matriculacion.Profesor')),
            ],
            options={
                'abstract': False,
            },
            bases=('matriculacion.profesor',),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.BooleanField(verbose_name='Clickea para seleccionar turno "Tarde"')),
            ],
        ),
        migrations.AddField(
            model_name='seccion',
            name='prof_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculacion.Profesor'),
        ),
        migrations.AddField(
            model_name='grado',
            name='turno_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Turno'),
        ),
    ]
