# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='cargo',
        ),
    ]
