# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 13:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Docente',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
