# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='sexo_t',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='sexo_t',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='sexo_t',
        ),
        migrations.AddField(
            model_name='director',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=True, max_length=6, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=32, max_length=6, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretaria',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=django.utils.timezone.now, max_length=6, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
