# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='aNo',
            field=models.IntegerField(verbose_name='1ero, 2do, etc...'),
        ),
    ]
