# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clave_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_logIn', models.IntegerField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('email_docente', models.EmailField(max_length=254)),
                ('dni_docente', models.IntegerField(max_length=10)),
                ('ingresado', models.BooleanField(default=False)),
            ],
        ),
    ]
