# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='cargo',
            field=models.CharField(default='ninguno', max_length=150, verbose_name='Cargo que posee en esta escuela'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='cargo',
            field=models.CharField(default=43, max_length=150, verbose_name='Cargo que posee en esta escuela'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretaria',
            name='cargo',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Cargo que posee en esta escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clave_docente',
            name='dni_docente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clave_docente',
            name='email_docente',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='curso',
            name='aNo',
            field=models.CharField(max_length=5, verbose_name='1ero, 2do, etc...'),
        ),
        migrations.AlterField(
            model_name='director',
            name='email_t',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email del trabajador'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email_t',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email del trabajador'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='email_t',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email del trabajador'),
        ),
    ]
