# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='prof_asignado',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
