# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='prof_asignado',
        ),
    ]
