# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-03 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(choices=[('Maniana', 'Maniana'), ('Tarde', 'Tarde')], max_length=15, verbose_name='Hora'),
        ),
    ]
