# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20180809_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='sexo',
        ),
        migrations.AddField(
            model_name='director',
            name='sexo_t',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=15, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo_t',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=43, max_length=15, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretaria',
            name='sexo_t',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default=3, max_length=15, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
