# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_remove_seccion_prof_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='prof_asignado',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='institucion.Profesor'),
            preserve_default=False,
        ),
    ]
