# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20180923_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='aNo',
            field=models.IntegerField(verbose_name='1,2,3,4...'),
        ),
    ]
