# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_clave_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clave_docente',
            name='clave_logIn',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(8)]),
        ),
    ]
