# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20180803_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.BooleanField(verbose_name='Clickea para seleccionar turno "Tarde"'),
        ),
    ]
