# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20181016_1140'),
        ('institucion', '0002_auto_20181016_1115'),
    ]

    operations = [
    ]
