# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucion', '0002_user_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secreataria_referenciada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institucion.Secretaria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user_Docente',
        ),
        migrations.CreateModel(
            name='user_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_referenciado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institucion.Profesor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
