# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_auto_20180816_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='antiguedad_en_empresa',
            field=models.DateField(null=True, verbose_name='Antiguedad en la Empresa'),
        ),
        migrations.AlterField(
            model_name='director',
            name='fecha_inicio_actividad',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio de Clases en el Colegio'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='antiguedad_en_empresa',
            field=models.DateField(null=True, verbose_name='Antiguedad en la Empresa'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_inicio_actividad',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio de Clases en el Colegio'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='antiguedad_en_empresa',
            field=models.DateField(null=True, verbose_name='Antiguedad en la Empresa'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='fecha_inicio_actividad',
            field=models.DateField(null=True, verbose_name='Fecha de Inicio de Clases en el Colegio'),
        ),
    ]
