# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_auto_20180806_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.BooleanField(verbose_name='Clickea para seleccionar turno "Tarde"')),
                ('aNo', models.CharField(max_length=5, verbose_name='1ero, 2do, etc...')),
                ('seccion', models.BooleanField(verbose_name='True = B o D, dependiendo de si es turno ma\xf1ana o tarde')),
            ],
        ),
        migrations.RemoveField(
            model_name='grado',
            name='turno_asignado',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='grado',
        ),
    ]
