# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_merge_20181016_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Cargo que posee en esta escuela'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Cargo que posee en esta escuela'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Cargo que posee en esta escuela'),
        ),
    ]
