# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_auto_20181023_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='cargo',
            field=models.CharField(blank=True, default='director', max_length=50, verbose_name='Cargo que posee en esta escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='director',
            name='email_t',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Email del trabajador'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='cargo',
            field=models.CharField(blank=True, default=43, max_length=50, verbose_name='Cargo que posee en esta escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email_t',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Email del trabajador'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='cargo',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, verbose_name='Cargo que posee en esta escuela'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='email_t',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Email del trabajador'),
        ),
    ]
