# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculacion', '0002_auto_20180807_1200'),
        ('institucion', '0004_auto_20180807_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grado',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institucion.Curso'),
            preserve_default=False,
        ),
    ]
