# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_auto_20180628_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='prof_asignado',
        ),
        migrations.AddField(
            model_name='seccion',
            name='prof_asignado',
            field=models.ManyToManyField(to='institucion.Profesor'),
        ),
    ]
