# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_auto_20181008_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='email_t',
            field=models.EmailField(max_length=70, verbose_name='Email del trabajador'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email_t',
            field=models.EmailField(max_length=70, verbose_name='Email del trabajador'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='email_t',
            field=models.EmailField(max_length=70, verbose_name='Email del trabajador'),
        ),
    ]
