# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0005_auto_20180628_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Profesor')),
            ],
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='prof_asignado',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='seccopm_asignada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.Seccion'),
        ),
    ]
