# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucion', '0005_auto_20180807_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_referenciado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institucion.Director')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
