# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0006_user_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_secretaria',
            old_name='secreataria_referenciada',
            new_name='secretaria_referenciada',
        ),
    ]
