# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0007_auto_20180628_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='seccopm_asignada',
            new_name='seccion_asignada',
        ),
    ]
