# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0005_auto_20180626_1335'),
        ('institucion', '0008_auto_20180628_1446'),
    ]

    operations = [
    ]
